[package]
name = "deasil"
version = "0.1.0"
authors = [
    "tatostao",
    "teki",
    "pierd",
]

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
rand = "0.5.5"
specs = "0.12.2"
specs-derive = "0.2.0"
